name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Especifica la versión de Node.js que quieres usar

      - name: Install dependencies
        run: |
          npm install --save-dev jest

      - name: Run tests
        run: |
          npx jest
